src/main/java/br/com/treinamento/pojo/Character.java
package br.com.treinamento.pojo;

import java.io.Serializable;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

@JsonIgnoreProperties(ignoreUnknown = true)
public class Character implements Serializable {

	private static final long serialVersionUID = 5693331415965546273L;

	private Integer id;

	private String name;

	private String description;
	
	private Thumbnail thumbnail;
	
	private Quantity comics;
	
	private Quantity series;
	
	private Quantity stories;

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Thumbnail getThumbnail() {
		return thumbnail;
	}

	public void setThumbnail(Thumbnail thumbnail) {
		this.thumbnail = thumbnail;
	}
	
	public Quantity getComics() {
		return comics;
	}

	public void setComics(Quantity comics) {
		this.comics = comics;
	}

	public Quantity getSeries() {
		return series;
	}

	public void setSeries(Quantity series) {
		this.series = series;
	}

	public Quantity getStories() {
		return stories;
	}

	public void setStories(Quantity stories) {
		this.stories = stories;
	}

	@Override
	public String toString() {
		return "Character [id=" + id + ", name=" + name + ", description=" + description + ", thumbnail=" + thumbnail
				+ ", comics=" + comics + ", series=" + series + ", stories=" + stories + "]";
	}

}

src/main/java/br/com/treinamento/pojo/Comics.java
package br.com.treinamento.pojo;

import java.io.Serializable;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

@JsonIgnoreProperties(ignoreUnknown = true)
public class Comics implements Serializable {

	@Override
	public String toString() {
		return "Comics [title=" + title + ", description=" + description + ", thumbnail=" + thumbnail + "]";
	}

	private static final long serialVersionUID = 8002721317341695166L;

	private String title;
	
	private String description;
	
	private Thumbnail thumbnail;

	public String getTitle() {
		return title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Thumbnail getThumbnail() {
		return thumbnail;
	}

	public void setThumbnail(Thumbnail thumbnail) {
		this.thumbnail = thumbnail;
	}
	
}

src/main/java/br/com/treinamento/pojo/Thumbnail.java
package br.com.treinamento.pojo;

import java.io.Serializable;

import br.com.treinamento.constant.Constants;

public class Thumbnail implements Serializable{

	@Override
	public String toString() {
		return "CharacterThumbnail [path=" + path + ", extension=" + extension + "]";
	}

	private static final long serialVersionUID = -2270564329626012330L;
	
	private String path;
	
	private String extension;

	public String getPath() {
		return path;
	}

	public void setPath(String path) {
		this.path = path;
	}

	public String getExtension() {
		return extension;
	}

	public void setExtension(String extension) {
		this.extension = extension;
	}
	
	/**
	 * Função para imprimir o path da imagem real
	 * Referência: https://developer.marvel.com/documentation/images 
	 * */
	public String getPathWithExtension() {
		return path + "/" + Constants.IMAGE_TYPE + "." + extension;
	}
}

src/main/webapp/WEB-INF/view/character.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ taglib prefix="spring" uri="http://www.springframework.org/tags"%>

<h1>Showing character</h1>

<pre>${time}</pre>

<table>
	<tr>
		<td>ID:</td>
		<td>${character.id}</td>
	</tr>
	<tr>
		<td>Name:</td>
		<td>${character.name}</td>
	</tr>
	<tr>
		<td>Description:</td>
		<td>${character.description}</td>
	</tr>
	<tr>
		<td>Image:</td>
		<td><img src="${character.thumbnail.pathWithExtension}"></td>
	</tr>
	<tr>
		<td>Number of Comics:</td>
		<td><a href=/character/${character.id}/comics/0>${character.comics}</a></td>
	</tr>
</table>

src/main/webapp/WEB-INF/view/characters.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ taglib prefix="spring" uri="http://www.springframework.org/tags"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>   

<h1>Showing Comics</h1>



<table border="2">
	<tr><th>ID</th><th>Name</th><th>Description</th><th>Image</th></tr>
	<c:forEach var="character" items="${characters}">
	<tr>
		<td><a href="/character/${character.id}">${character.id}</a></td>
		<td>${character.name}</td>
		<td>${character.description}</td>
		<td><img src="${character.thumbnail.pathWithExtension}"></td>
	</tr>
	</c:forEach>
</table>

src/main/webapp/WEB-INF/view/comics.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ taglib prefix="spring" uri="http://www.springframework.org/tags"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>   

<h1>Showing Comics</h1>



<table border="2">
	<tr><th>Title</th><th>Description</th><th>Image</th></tr>
	<c:forEach var="comic" items="${comics}">
	<tr>
		<td>${comic.title}</td>
		<td>${comic.description}</td>
		<td><img src="${comic.thumbnail.pathWithExtension}"></td>
	</tr>
	</c:forEach>  
	<c:if test = "${previous >= 0}">
		<a href=/character/${characId}/comics/${previous}> <-Previous </a>
	</c:if>
	<c:if test = "${comicsSize == 20}">
		<a href=/character/${characId}/comics/${next}> Next -></a>
	</c:if>
</table>

src/main/webapp/WEB-INF/view/index.jsp
<%@ taglib uri="http://www.springframework.org/tags/form" prefix="form"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>

<h1>Search Characters</h1>
<form action="/characters" method="get">
  Name Starts with:<input type="text" name="name"><br>
  <input type="submit" value="Submit">
</form>